import distutils.sysconfig
import numpy

env = Environment(CPPPATH=[distutils.sysconfig.get_python_inc()])

CyBuilder = env.Command('CySim.cpp','CySim.pyx','cython --cplus -o $TARGET $SOURCE')
EIGENDIR = ARGUMENTS.get('EIGENDIR')
env.Append(CPPPATH=[EIGENDIR, numpy.get_include()])
CyModule = env.SharedLibrary('CySim', ['CPPBackEnd.cpp', CyBuilder])

